/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javacrud.view;

import java.io.IOException;
import java.sql.Connection;
import java.sql.Statement;
import java.util.Arrays;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javacrud.control.ConfigDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javacrud.model.Utilisateur;
import javacrud.control.UtilisateurDAOImp;
import javacrud.model.Commune;
import javacrud.model.Configuration;
import javacrud.control.ImageDAO;
import javax.swing.ImageIcon;
import javacrud.tech.PDF;


public class UtilCrud extends javax.swing.JFrame {
   
    /**
     * Creates new form UtilCrud
     */
    Connection con;
    Statement st;
    TreeMap<String, Utilisateur> lesUtilisateurs = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
    UtilisateurDAOImp dao = new UtilisateurDAOImp();
    String uiNumpost;
    private Commune selectedville;
    Utilisateur utilisateur = new Utilisateur();

    private void chargerLesUtilisateurs() {
        lesUtilisateurs.clear();
        lesUtilisateurs = dao.list();
        chargerTableauUtilisateurs();
    }

    private void chargerTableauUtilisateurs() {
        DefaultTableModel uiTable = (DefaultTableModel) tbUtilisateur.getModel();
        int j = uiTable.getRowCount();
        System.out.println(j);
        for (int i = j - 1; i >= 0; i--) {
            uiTable.removeRow(i);
        }
        for (String pseudo : lesUtilisateurs.keySet()) {
            Utilisateur unUtilisateur = lesUtilisateurs.get(pseudo);
            Object[] row = new Object[3];
            row[0] = unUtilisateur.getUt_nom();
            row[1] = unUtilisateur.getUt_prenom();
            row[2] = unUtilisateur.getUt_pseudo();
            uiTable.addRow(row);
        }
    }

    public void changeSelectUt() {
        int i = tbUtilisateur.getSelectedRow();
        TableModel model = tbUtilisateur.getModel();
        Utilisateur unUtilisateur = lesUtilisateurs.get(model.getValueAt(i, 2).toString());
        uiNom.setText(unUtilisateur.getUt_nom());
        uiPrenom.setText(unUtilisateur.getUt_prenom());
        uiPseudo.setText(unUtilisateur.getUt_pseudo());
        uiMail.setText(unUtilisateur.getUt_mail());
        uiMP.setText(unUtilisateur.getUt_mp());
        uiAdr1.setText(unUtilisateur.getUt_adr1());
        uiAdr2.setText(unUtilisateur.getUt_adr2());
        uiCp.setText(unUtilisateur.getUt_cdpost());
        uiVille.setText(unUtilisateur.getUt_nomCommune());
        chargePhotoUt();
    }

    public void changeSelectUtNull() {
        uiNom.setText(null);
        uiPrenom.setText(null);
        uiPseudo.setText(null);
        uiMail.setText(null);
        uiMP.setText(null);
        uiAdr1.setText(null);
        uiAdr2.setText(null);
        uiCp.setText(null);
        uiVille.setText(null);
    }

    public void alert(String msg) {
        JOptionPane.showMessageDialog(rootPane, msg);
        Message.setForeground(new java.awt.Color(51, 102, 0));
        Message.setText(msg);

    }

    public void alert(String msg, String titre) {
        JOptionPane.showMessageDialog(rootPane, msg, titre, JOptionPane.ERROR_MESSAGE);
        Message.setForeground(new java.awt.Color(204, 0, 51));
        Message.setText(msg);
    }

    public UtilCrud() {
        initComponents();
        Message.setText("Veuillez choisir un utilisateur dans le tableau de droite ou saisir les données à créer");
        chargerLesUtilisateurs();
    }

    private void chargePhotoUt() {
        ImageIcon photo = ImageDAO.getUtIcon(this.uiPseudo.getText());
        if (photo != null) {
            this.avatar.setIcon(photo);
        } else {
            this.avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/user-tie_.jpg")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Adresse = new javax.swing.JPanel();
        jLabelNom = new javax.swing.JLabel();
        uiNom = new javax.swing.JTextField();
        jLabelPrenom = new javax.swing.JLabel();
        uiPrenom = new javax.swing.JTextField();
        jLabelPseudo = new javax.swing.JLabel();
        uiPseudo = new javax.swing.JTextField();
        jLabelMail = new javax.swing.JLabel();
        uiMail = new javax.swing.JTextField();
        jLabelMP = new javax.swing.JLabel();
        uiMP = new javax.swing.JTextField();
        Creer = new javax.swing.JButton();
        Modifier = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        Vider = new javax.swing.JButton();
        uiAdr1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        uiAdr2 = new javax.swing.JTextField();
        uiCp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Ville = new javax.swing.JButton();
        uiVille = new javax.swing.JTextField();
        avatar = new javax.swing.JLabel();
        PhotoBouton = new javax.swing.JButton();
        pdf = new javax.swing.JButton();
        tbScrollPane = new javax.swing.JScrollPane();
        tbUtilisateur = new javax.swing.JTable();
        Entete = new javax.swing.JLabel();
        Parametre = new javax.swing.JButton();
        Quitter = new javax.swing.JButton();
        Background = new javax.swing.JLabel();
        Message = new javax.swing.JLabel();
        uiPhrase = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(860, 550));
        getContentPane().setLayout(null);

        Adresse.setOpaque(false);

        jLabelNom.setText("Nom : ");

        jLabelPrenom.setText("Prénom");

        uiPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiPrenomActionPerformed(evt);
            }
        });

        jLabelPseudo.setText("Utilisateur");

        jLabelMail.setText("Mail");

        jLabelMP.setText("Mot de Passe");

        Creer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/plus_20.png"))); // NOI18N
        Creer.setText("Creer");
        Creer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreerMouseClicked(evt);
            }
        });
        Creer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreerActionPerformed(evt);
            }
        });

        Modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/pencil_20.png"))); // NOI18N
        Modifier.setText("Modifier");
        Modifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifierMouseClicked(evt);
            }
        });
        Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierActionPerformed(evt);
            }
        });

        Supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/minus_20.png"))); // NOI18N
        Supprimer.setText("Supprimer");
        Supprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupprimerMouseClicked(evt);
            }
        });

        Vider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/eye-slash_20.png"))); // NOI18N
        Vider.setText("Nouveau");
        Vider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViderMouseClicked(evt);
            }
        });

        uiAdr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiAdr1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Adresse");

        uiCp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiCpActionPerformed(evt);
            }
        });

        jLabel3.setText("Code Postal");

        Ville.setText("Ville");
        Ville.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VilleMouseClicked(evt);
            }
        });
        Ville.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VilleActionPerformed(evt);
            }
        });

        avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/user-tie-min.jpg"))); // NOI18N
        avatar.setText("jLabel4");
        avatar.setMaximumSize(new java.awt.Dimension(142, 167));
        avatar.setMinimumSize(new java.awt.Dimension(142, 167));
        avatar.setPreferredSize(new java.awt.Dimension(142, 167));

        PhotoBouton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/user-img_20.png"))); // NOI18N
        PhotoBouton.setText("Photo");
        PhotoBouton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PhotoBoutonMouseClicked(evt);
            }
        });

        pdf.setText("PDF");
        pdf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pdfMouseClicked(evt);
            }
        });
        pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdresseLayout = new javax.swing.GroupLayout(Adresse);
        Adresse.setLayout(AdresseLayout);
        AdresseLayout.setHorizontalGroup(
            AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdresseLayout.createSequentialGroup()
                .addGroup(AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdresseLayout.createSequentialGroup()
                        .addContainerGap(28, Short.MAX_VALUE)
                        .addComponent(uiVille, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ville)
                        .addGap(69, 69, 69))
                    .addGroup(AdresseLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uiAdr2)
                            .addComponent(uiAdr1)))
                    .addGroup(AdresseLayout.createSequentialGroup()
                        .addGroup(AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(AdresseLayout.createSequentialGroup()
                                    .addGroup(AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelNom)
                                        .addComponent(jLabelPrenom))
                                    .addGap(40, 40, 40)
                                    .addGroup(AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(uiPrenom)
                                        .addComponent(uiNom)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdresseLayout.createSequentialGroup()
                                    .addGroup(AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelPseudo)
                                        .addComponent(jLabelMail))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(uiMail, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(uiPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(AdresseLayout.createSequentialGroup()
                                    .addComponent(Creer)
                                    .addGap(26, 26, 26)
                                    .addComponent(Modifier)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(AdresseLayout.createSequentialGroup()
                                    .addComponent(jLabelMP)
                                    .addGap(10, 10, 10)
                                    .addComponent(uiMP, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(AdresseLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(uiCp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(AdresseLayout.createSequentialGroup()
                                .addComponent(Supprimer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Vider)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdresseLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdresseLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PhotoBouton)
                        .addGap(41, 41, 41))))
        );
        AdresseLayout.setVerticalGroup(
            AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdresseLayout.createSequentialGroup()
                .addGroup(AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdresseLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNom)
                            .addComponent(uiNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrenom)
                            .addComponent(uiPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPseudo)
                            .addComponent(uiPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMail)
                            .addComponent(uiMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMP)
                            .addComponent(uiMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AdresseLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdresseLayout.createSequentialGroup()
                        .addComponent(uiAdr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uiAdr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(PhotoBouton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uiCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uiVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ville))
                .addGap(18, 18, 18)
                .addGroup(AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Creer)
                    .addComponent(Modifier)
                    .addComponent(pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Supprimer)
                    .addComponent(Vider))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Adresse);
        Adresse.setBounds(330, 60, 500, 410);

        tbScrollPane.setOpaque(false);
        tbScrollPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbScrollPaneMouseClicked(evt);
            }
        });

        tbUtilisateur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prénom", "Utilisateur"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbUtilisateur.setOpaque(false);
        tbUtilisateur.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbUtilisateur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUtilisateurMouseClicked(evt);
            }
        });
        tbUtilisateur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbUtilisateurKeyReleased(evt);
            }
        });
        tbScrollPane.setViewportView(tbUtilisateur);
        if (tbUtilisateur.getColumnModel().getColumnCount() > 0) {
            tbUtilisateur.getColumnModel().getColumn(2).setResizable(false);
        }
        tbUtilisateur.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(tbScrollPane);
        tbScrollPane.setBounds(10, 80, 310, 298);

        Entete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/java_64.png"))); // NOI18N
        Entete.setText("Gestion Client");
        getContentPane().add(Entete);
        Entete.setBounds(0, -10, 800, 70);

        Parametre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/wrench._20.png"))); // NOI18N
        Parametre.setText("Paramètre");
        Parametre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ParametreMouseClicked(evt);
            }
        });
        getContentPane().add(Parametre);
        Parametre.setBounds(20, 500, 140, 29);

        Quitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/escape_20.png"))); // NOI18N
        Quitter.setText("Quitter");
        Quitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuitterMouseClicked(evt);
            }
        });
        getContentPane().add(Quitter);
        Quitter.setBounds(700, 500, 91, 29);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/back_ec.jpg"))); // NOI18N
        Background.setText("jLabel2");
        getContentPane().add(Background);
        Background.setBounds(0, 60, 870, 480);

        Message.setText("jLabel4");
        getContentPane().add(Message);
        Message.setBounds(260, 400, 34, 14);

        uiPhrase.setText("jLabel4");
        getContentPane().add(uiPhrase);
        uiPhrase.setBounds(280, 450, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbUtilisateurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUtilisateurMouseClicked
        changeSelectUt();
    }//GEN-LAST:event_tbUtilisateurMouseClicked

    private void tbUtilisateurKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbUtilisateurKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tbUtilisateurKeyReleased

    private void tbScrollPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbScrollPaneMouseClicked

    }//GEN-LAST:event_tbScrollPaneMouseClicked

    private void uiCpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiCpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiCpActionPerformed

    private void uiAdr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiAdr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiAdr1ActionPerformed

    private void CreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreerActionPerformed

    private void uiPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiPrenomActionPerformed

    private void ViderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViderMouseClicked
        changeSelectUtNull();
    }//GEN-LAST:event_ViderMouseClicked

    private void SupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupprimerMouseClicked
        Utilisateur unUtilisateur = new Utilisateur();
        String pseudo = uiPseudo.getText();
        unUtilisateur.setUt_pseudo(pseudo);
        unUtilisateur.setUt_nom(uiNom.getText());
        unUtilisateur.setUt_prenom(uiPrenom.getText());
        unUtilisateur.setUt_mp(uiMP.getText());
        unUtilisateur.setUt_mail(uiMail.getText());
        unUtilisateur.setUt_adr1(uiAdr1.getText());
        unUtilisateur.setUt_adr2(uiAdr2.getText());
        unUtilisateur.setUt_cdpost(uiCp.getText());
        unUtilisateur.setUt_numpost(uiNumpost);

        dao.delete(unUtilisateur);

        lesUtilisateurs.remove(pseudo);
        chargerTableauUtilisateurs();

    }//GEN-LAST:event_SupprimerMouseClicked

    private void ModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifierMouseClicked
        Utilisateur unUtilisateur = new Utilisateur();
        String pseudo = uiPseudo.getText();
        String mdp = uiMP.getText();
        String phrase = unUtilisateur.updateUtMp(mdp);
        unUtilisateur.setUt_pseudo(pseudo);
        unUtilisateur.setUt_nom(uiNom.getText());
        unUtilisateur.setUt_prenom(uiPrenom.getText());
        unUtilisateur.setUt_mp(uiMP.getText());
        unUtilisateur.setUt_phrase(phrase);
        unUtilisateur.setUt_mail(uiMail.getText());
        unUtilisateur.setUt_adr1(uiAdr1.getText());
        unUtilisateur.setUt_adr2(uiAdr2.getText());
        unUtilisateur.setUt_cdpost(uiCp.getText());
        unUtilisateur.setUt_numpost(uiNumpost);

        chargerTableauUtilisateurs();
        dao.update(unUtilisateur);
    }//GEN-LAST:event_ModifierMouseClicked

    private void CreerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreerMouseClicked
        Utilisateur unUtilisateur = new Utilisateur();
        String pseudo = uiPseudo.getText();
        String mdp = uiMP.getText();
        String phrase = unUtilisateur.updateUtMp(mdp);
        unUtilisateur.setUt_pseudo(pseudo);
        unUtilisateur.setUt_nom(uiNom.getText());
        unUtilisateur.setUt_prenom(uiPrenom.getText());
        unUtilisateur.setUt_mp(uiMP.getText());
        unUtilisateur.setUt_phrase(phrase);
        unUtilisateur.setUt_mail(uiMail.getText());
        unUtilisateur.setUt_adr1(uiAdr1.getText());
        unUtilisateur.setUt_adr2(uiAdr2.getText());
        unUtilisateur.setUt_cdpost(uiCp.getText());
        unUtilisateur.setUt_numpost(uiNumpost);

        lesUtilisateurs.put(pseudo, unUtilisateur);

        chargerTableauUtilisateurs();
        dao.create(unUtilisateur);

    }//GEN-LAST:event_CreerMouseClicked

    private void VilleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VilleMouseClicked
        if (uiCp.getText().strip().length() == 5) {
            SelectionVille selVille;
            selVille = new SelectionVille(new javax.swing.JFrame(), true, Integer.parseInt(uiCp.getText()), uiNumpost);

            selVille.setVisible(true);
            this.selectedville = selVille.getSelectedVille();
            //selVille = null;
            if (selVille.getSelected()) {
                uiNumpost = selectedville.getNum_Postal();
                uiVille.setText(selectedville.getNom_Commune());
            } else {
                alert("Le code postal doit contenir au moins 5 chiffres");
            }

        }

    }//GEN-LAST:event_VilleMouseClicked

    private void VilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VilleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VilleActionPerformed

    private void ParametreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ParametreMouseClicked
        Parametres c;
        ConfigDAO conf;
        try {
            conf = new ConfigDAO();
            c = new Parametres(new javax.swing.JFrame(), true);
            c.setVisible(true);

        } catch (Exception ex) {
            Logger.getLogger(UtilCrud.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_ParametreMouseClicked

    private void QuitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitterMouseClicked
        System.exit(0);
    }//GEN-LAST:event_QuitterMouseClicked

    private void ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifierActionPerformed

    private void PhotoBoutonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhotoBoutonMouseClicked
        SelectAvatar avatar;
        
        avatar = new SelectAvatar(new javax.swing.JFrame(), true, uiPseudo.getText());
        avatar.setVisible(true);
        if(avatar.isSelected()){
            chargePhotoUt();
        }
    }//GEN-LAST:event_PhotoBoutonMouseClicked

    private void pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdfActionPerformed

    private void pdfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdfMouseClicked
        PDF monpdf = new PDF();
        try {
            monpdf.createPDF(uiNom.getText(), uiPrenom.getText(), uiPseudo.getText(), uiMail.getText(), uiAdr1.getText(), uiAdr2.getText(), uiCp.getText(), uiVille.getText());
        } catch (IOException ex) {
            
        }
            
    }//GEN-LAST:event_pdfMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UtilCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UtilCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UtilCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UtilCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UtilCrud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Adresse;
    private javax.swing.JLabel Background;
    private javax.swing.JButton Creer;
    private javax.swing.JLabel Entete;
    private javax.swing.JLabel Message;
    private javax.swing.JButton Modifier;
    private javax.swing.JButton Parametre;
    private javax.swing.JButton PhotoBouton;
    private javax.swing.JButton Quitter;
    private javax.swing.JButton Supprimer;
    private javax.swing.JButton Vider;
    private javax.swing.JButton Ville;
    private javax.swing.JLabel avatar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelMP;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelPseudo;
    private javax.swing.JButton pdf;
    private javax.swing.JScrollPane tbScrollPane;
    private javax.swing.JTable tbUtilisateur;
    private javax.swing.JTextField uiAdr1;
    private javax.swing.JTextField uiAdr2;
    private javax.swing.JTextField uiCp;
    private javax.swing.JTextField uiMP;
    private javax.swing.JTextField uiMail;
    private javax.swing.JTextField uiNom;
    private javax.swing.JLabel uiPhrase;
    private javax.swing.JTextField uiPrenom;
    private javax.swing.JTextField uiPseudo;
    private javax.swing.JTextField uiVille;
    // End of variables declaration//GEN-END:variables
}
